### ISSUE TITLE
3.txt, and other languages

### ISSUE THREAD

**Issue by ExoBen** [Dr-Lord/Sudoku-Solver#1]
a) just wondering what on earth 3.txt actually contains and b) wondering if you wrote this in python and if so if you can upload it for me to compare to my nearly finished one - Thanks :)

**Comment by T-Flet** [comment]
a) It contains linearised Sudokus with 30 numbers to start with: some test data, which can be formatted into classic Sudokus by the SudokuExtractor.
b) No, I have not, but there are at least 4 different solving algorithms in this version, each of increasing "power", the one you used might be among them.
